url: "http://jiefool.github.io/"
baseurl: ""

# Site settings
title: BICTC
phone: (+6338) 412-4559
email: boholipc@gmail.com
description: "Bohol Information and Communication Technology Council"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 4DA6E7
  secondary: 75bbed  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Joanne Phillips
  pic: joannep
  position: President
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Benjamin Skelton
  pic: ben
  position: Vice President, Game Development & Animation
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Ace Lumaad
  pic: acel
  position: Software Development
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Bryan Jatico Agua
  pic: bryana
  position: Freelancers
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Jerome Auza
  pic: jerome
  position: Software Development
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Monica Jane Roldan
  pic: monicar
  position: E-Commerce & ICT Dealers, Entrepreneurship
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Nelson Buena
  pic: nelsonb
  position: Web Development
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Nizah Bagares
  pic: nizahb
  position: Seminars, Training and Workshops
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Ric Obedencio
  pic: rico
  position: Photo Journalism
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Roy E. Bayonas
  pic: roy
  position: Startup Community
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Thomas Ridenour
  pic: thomasr
  position: Digital Marketing
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Zion Campo
  pic: zionc
  position: Global Shapers, IdeaSpace, Startup Weekend, Press Relations
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/jaypaulaying
  - title: facebook
    url: https://www.facebook.com/pages/Bohol-ICT-Council/298406196882599?fref=ts
  - title: linkedin
    url: 
# Postal address (add as many lines as necessary)
address:
  - line: Governor's Mansion
  - line: Bohol 6300, Philippines

# Build settings
markdown: kramdown
permalink: pretty
